CREATE DATABASE BOOK;

SHOW DATABASES;

USE BOOK;

CREATE TABLE BOOK.TABELA(
ID INT AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
AUTOR VARCHAR (255) NOT NULL,
SEXO  VARCHAR (25) NOT NULL,
NUMERO_DE_PAGINAS INT NOT NULL,
EDITORA VARCHAR (255) NOT NULL,
VALOR_CAPA_COMUM INT NOT NULL,
VALOR_KINDLE INT NOT NULL,
ANO INT NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('PAI RICO, PAI POBRE', 'ROBERT T.KIYOUSAKI ', 'MASCULINO', 336,'ALTA BOOKS', 61.5 , 58.45, 2018);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('MINDSET', 'CAROL S DWECK ', 'FEMININO', 312,'OBJETIVA',38.99, 14.95, 2017);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('COMO FAZER AMIGOS E INFLUENCIAR PESSOAS', 'DALE CANEGIE','MASCULINO', 256,'SEXTANTE',38.99, 33.24, 2019);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('A CABANA', 'WILLIAM P YOUNG', 'MASCULINO', 240,'ARQUEIRO',35.99, 17.90, 2008);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('O PODER DO HABITO', 'CHARLES DUHIGG', 'MASCULINO', 408,'OBJETIVA',42.99, 29.90, 2012);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('CODIGO LIMPO', 'ROBERT C MARTIN', 'MASCULINO', 425,'ALTA BOOKS',91.99, 87.39, 2009);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('ESSENCIALISMO', 'GREG MCKEOWN ', 'MASCULINO', 272,'SEXTANTE',53.58, 33.24, 2015);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('ME POUPE!', 'NATHALIA ARCURI ', 'FEMININO', 176,'SEXTANTE',32.86, 17.09, 2018);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('COMECE PELO PORQUE', 'SIMON SINEK ', 'MASCULINO', 256,'SEXTANTE',50.58, 24.91, 2018);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('O ALQUIMISTA', 'PAULO COELHO', 'MASCULINO', 206,'PARALELA',24.70, 14.70, 2017);
-- SEGUNDA ATIVIDADE
-- Trazer o nome do livro, autor e valor Kindle somente de livros com valores menores que R$ 40,00;
SELECT ID, NOME, AUTOR, VALOR_KINDLE FROM TABELA WHERE VALOR_KINDLE <= 40;
-- Trazer o nome do livro e autor onde o ano de publicação seja maior que 2017, a editora seja Sextante e o sexo do autor seja feminino;
SELECT ID, NOME, AUTOR, ANO, EDITORA, SEXO FROM TABELA WHERE ANO >= 2017 AND EDITORA = 'SEXTANTE' AND SEXO ='FEMININO';
-- Trazer o nome do livro e editora de livros com mais de 200 páginas;
SELECT ID, NOME, EDITORA, NUMERO_DE_PAGINAS FROM TABELA WHERE NUMERO_DE_PAGINAS >= 200;
-- Trazer o nome do livro, número de páginas do livro e autores que começam com a letra "C";
SELECT NOME, NUMERO_DE_PAGINAS, AUTOR FROM TABELA WHERE AUTOR  LIKE 'C%';
-- Trazer o nome do autor, editora e ano de publicação dos livros que tenham autores do sexo masculino e tenham sido publicados pela editora Alta Books;
SELECT AUTOR, EDITORA, ANO, SEXO FROM TABELA WHERE SEXO = 'MASCULINO' AND EDITORA ='ALTA BOOKS';
-- Trazer o nome do livro, do autor, número de páginas, editora, ano de publicação e valor com capa comum com valores acima de R$ 50,00;
SELECT ID, NOME, AUTOR, NUMERO_DE_PAGINAS, EDITORA, ANO, VALOR_CAPA_COMUM FROM TABELA WHERE VALOR_CAPA_COMUM  >= 50;
--  Trazer o nome do livro, editora e valor capa comum onde o nome do autor comece com Nathalia;
SELECT ID, NOME, AUTOR, VALOR_CAPA_COMUM FROM TABELA WHERE AUTOR LIKE 'NATHALIA%';
--  Trazer o nome do livro, autor, número de páginas dos livros publicados até 2017;
SELECT ID, NOME, AUTOR, NUMERO_DE_PAGINAS, ANO FROM TABELA WHERE ANO <= 2017;
-- Trazer o nome dos autores com livros publicados pela editora Sextante com mais de 200 páginas;
SELECT ID, AUTOR, EDITORA, NUMERO_DE_PAGINAS FROM TABELA WHERE EDITORA ='SEXTANTE' AND NUMERO_DE_PAGINAS >= 200;
-- Trazer o nome do livro, autores, valor com capa comum com valor maior que R$ 30,00 na editora Sextante;
SELECT NOME, AUTOR, VALOR_CAPA_COMUM, EDITORA FROM TABELA WHERE VALOR_CAPA_COMUM >= 30 AND EDITORA = 'SEXTANTE';
-- PRIMEIRA ATIVIDADE
-- SELECIONAR TODAS AS TABELAS+
SELECT * FROM BOOK.TABELA;

 -- SELECIONA APENAS ID, NOME E EDITORA +
SELECT ID, NOME, EDITORA FROM BOOK.TABELA;

-- MOSTRA ID, EDITORA E SEXO MASCULINO +
SELECT ID, EDITORA, SEXO FROM TABELA WHERE SEXO = 'MASCULINO';

-- MOSTRA NOME, PAGINAS E SEXO FEMININO +
SELECT ID, NOME, NUMERO_DE_PAGINAS, SEXO FROM TABELA WHERE SEXO = 'FEMININO';

-- MOSTRA NOME, EDITORA, ANO A PARTI DE 2017 +
SELECT ID, NOME, ANO FROM TABELA WHERE ANO >= 2017;

-- MOSTRAR NOME, SEXO MASCULINO, EDITORA SEXTANTE OU ALTA BOOKS+
SELECT ID, NOME, SEXO, EDITORA FROM TABELA WHERE SEXO = 'MASCULINO' AND EDITORA = 'SEXTANTE' OR 'ALTA BOOKS';

-- MOSTRAR NOME, AUTOR, NUMERO DE PAGINAS, EDITORA, ANO E VALOR CAPA COMUM+
SELECT ID, NOME, AUTOR, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, ANO FROM TABELA; 

-- MOSTRAR NOME, AUTOR, NUMERO DE PAGINAS, VALOR KINDLE+
SELECT ID, NOME, AUTOR, NUMERO_DE_PAGINAS, VALOR_KINDLE FROM TABELA;

-- MOSTRAR AUTOR, NOME, EDITORA+
SELECT ID, AUTOR, EDITORA, NOME FROM TABELA WHERE EDITORA = 'SEXTANTE';

-- MOSTRAR NOME, AUTOR, VALOR DA CAPA COMUM E DO KINDLE;
SELECT ID, NOME, AUTOR, VALOR_CAPA_COMUM, VALOR_KINDLE FROM TABELA;

-- TRUNCATE TABELA; --APAGA A TABELA